# Generated by Django 4.1.4 on 2023-01-29 19:28

from django.db import migrations, models
import django.db.models.deletion
import findin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custommer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('industry', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('birthday', models.DateField(max_length=20)),
                ('useraddress', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AnnonceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreAnn', models.CharField(max_length=50)),
                ('catégorie', models.CharField(max_length=50)),
                ('théme', models.CharField(max_length=100)),
                ('modalité', models.CharField(max_length=10)),
                ('Description', models.CharField(max_length=500)),
                ('tarif', models.CharField(max_length=200)),
                ('Wilaya', models.CharField(max_length=200)),
                ('Commune', models.CharField(max_length=200)),
                ('adresseIMB', models.CharField(max_length=1000)),
                ('adresseURL', models.CharField(max_length=1000)),
                ('image_url', models.ImageField(blank=True, upload_to=findin.models.upload_to)),
                ('annonceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findin.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='Annfav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='findin.usermodel')),
                ('titreAnnfav', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='findin.annoncemodel')),
            ],
        ),
    ]
