# Generated by Django 4.1.4 on 2023-01-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findin', '0002_annoncemodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoncemodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
